language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - pip install numpy

script:
  - cd src/
  - python -m pytest --verbose --doctest-modules .
  - python -m pytest --verbose ../test
