# AUTOGENERATED, DO NOT EDIT!


def expand_function_autogen(f, argspec):
    if argspec == "x_x":
        def result(x, y, z):
            x = f(x)
            return x, y, z

        return result

    if argspec == "y_x":
        def result(x, y, z):
            y = f(x)
            return x, y, z

        return result

    if argspec == "z_x":
        def result(x, y, z):
            z = f(x)
            return x, y, z

        return result

    if argspec == "xy_x":
        def result(x, y, z):
            x, y = f(x)
            return x, y, z

        return result

    if argspec == "xz_x":
        def result(x, y, z):
            x, z = f(x)
            return x, y, z

        return result

    if argspec == "yx_x":
        def result(x, y, z):
            y, x = f(x)
            return x, y, z

        return result

    if argspec == "yz_x":
        def result(x, y, z):
            y, z = f(x)
            return x, y, z

        return result

    if argspec == "zx_x":
        def result(x, y, z):
            z, x = f(x)
            return x, y, z

        return result

    if argspec == "zy_x":
        def result(x, y, z):
            z, y = f(x)
            return x, y, z

        return result

    if argspec == "xyz_x":
        def result(x, y, z):
            x, y, z = f(x)
            return x, y, z

        return result

    if argspec == "xzy_x":
        def result(x, y, z):
            x, z, y = f(x)
            return x, y, z

        return result

    if argspec == "yxz_x":
        def result(x, y, z):
            y, x, z = f(x)
            return x, y, z

        return result

    if argspec == "yzx_x":
        def result(x, y, z):
            y, z, x = f(x)
            return x, y, z

        return result

    if argspec == "zxy_x":
        def result(x, y, z):
            z, x, y = f(x)
            return x, y, z

        return result

    if argspec == "zyx_x":
        def result(x, y, z):
            z, y, x = f(x)
            return x, y, z

        return result

    if argspec == "x_y":
        def result(x, y, z):
            x = f(y)
            return x, y, z

        return result

    if argspec == "y_y":
        def result(x, y, z):
            y = f(y)
            return x, y, z

        return result

    if argspec == "z_y":
        def result(x, y, z):
            z = f(y)
            return x, y, z

        return result

    if argspec == "xy_y":
        def result(x, y, z):
            x, y = f(y)
            return x, y, z

        return result

    if argspec == "xz_y":
        def result(x, y, z):
            x, z = f(y)
            return x, y, z

        return result

    if argspec == "yx_y":
        def result(x, y, z):
            y, x = f(y)
            return x, y, z

        return result

    if argspec == "yz_y":
        def result(x, y, z):
            y, z = f(y)
            return x, y, z

        return result

    if argspec == "zx_y":
        def result(x, y, z):
            z, x = f(y)
            return x, y, z

        return result

    if argspec == "zy_y":
        def result(x, y, z):
            z, y = f(y)
            return x, y, z

        return result

    if argspec == "xyz_y":
        def result(x, y, z):
            x, y, z = f(y)
            return x, y, z

        return result

    if argspec == "xzy_y":
        def result(x, y, z):
            x, z, y = f(y)
            return x, y, z

        return result

    if argspec == "yxz_y":
        def result(x, y, z):
            y, x, z = f(y)
            return x, y, z

        return result

    if argspec == "yzx_y":
        def result(x, y, z):
            y, z, x = f(y)
            return x, y, z

        return result

    if argspec == "zxy_y":
        def result(x, y, z):
            z, x, y = f(y)
            return x, y, z

        return result

    if argspec == "zyx_y":
        def result(x, y, z):
            z, y, x = f(y)
            return x, y, z

        return result

    if argspec == "x_z":
        def result(x, y, z):
            x = f(z)
            return x, y, z

        return result

    if argspec == "y_z":
        def result(x, y, z):
            y = f(z)
            return x, y, z

        return result

    if argspec == "z_z":
        def result(x, y, z):
            z = f(z)
            return x, y, z

        return result

    if argspec == "xy_z":
        def result(x, y, z):
            x, y = f(z)
            return x, y, z

        return result

    if argspec == "xz_z":
        def result(x, y, z):
            x, z = f(z)
            return x, y, z

        return result

    if argspec == "yx_z":
        def result(x, y, z):
            y, x = f(z)
            return x, y, z

        return result

    if argspec == "yz_z":
        def result(x, y, z):
            y, z = f(z)
            return x, y, z

        return result

    if argspec == "zx_z":
        def result(x, y, z):
            z, x = f(z)
            return x, y, z

        return result

    if argspec == "zy_z":
        def result(x, y, z):
            z, y = f(z)
            return x, y, z

        return result

    if argspec == "xyz_z":
        def result(x, y, z):
            x, y, z = f(z)
            return x, y, z

        return result

    if argspec == "xzy_z":
        def result(x, y, z):
            x, z, y = f(z)
            return x, y, z

        return result

    if argspec == "yxz_z":
        def result(x, y, z):
            y, x, z = f(z)
            return x, y, z

        return result

    if argspec == "yzx_z":
        def result(x, y, z):
            y, z, x = f(z)
            return x, y, z

        return result

    if argspec == "zxy_z":
        def result(x, y, z):
            z, x, y = f(z)
            return x, y, z

        return result

    if argspec == "zyx_z":
        def result(x, y, z):
            z, y, x = f(z)
            return x, y, z

        return result

    if argspec == "x_xy":
        def result(x, y, z):
            x = f(x, y)
            return x, y, z

        return result

    if argspec == "y_xy":
        def result(x, y, z):
            y = f(x, y)
            return x, y, z

        return result

    if argspec == "z_xy":
        def result(x, y, z):
            z = f(x, y)
            return x, y, z

        return result

    if argspec == "xy_xy":
        def result(x, y, z):
            x, y = f(x, y)
            return x, y, z

        return result

    if argspec == "xz_xy":
        def result(x, y, z):
            x, z = f(x, y)
            return x, y, z

        return result

    if argspec == "yx_xy":
        def result(x, y, z):
            y, x = f(x, y)
            return x, y, z

        return result

    if argspec == "yz_xy":
        def result(x, y, z):
            y, z = f(x, y)
            return x, y, z

        return result

    if argspec == "zx_xy":
        def result(x, y, z):
            z, x = f(x, y)
            return x, y, z

        return result

    if argspec == "zy_xy":
        def result(x, y, z):
            z, y = f(x, y)
            return x, y, z

        return result

    if argspec == "xyz_xy":
        def result(x, y, z):
            x, y, z = f(x, y)
            return x, y, z

        return result

    if argspec == "xzy_xy":
        def result(x, y, z):
            x, z, y = f(x, y)
            return x, y, z

        return result

    if argspec == "yxz_xy":
        def result(x, y, z):
            y, x, z = f(x, y)
            return x, y, z

        return result

    if argspec == "yzx_xy":
        def result(x, y, z):
            y, z, x = f(x, y)
            return x, y, z

        return result

    if argspec == "zxy_xy":
        def result(x, y, z):
            z, x, y = f(x, y)
            return x, y, z

        return result

    if argspec == "zyx_xy":
        def result(x, y, z):
            z, y, x = f(x, y)
            return x, y, z

        return result

    if argspec == "x_xz":
        def result(x, y, z):
            x = f(x, z)
            return x, y, z

        return result

    if argspec == "y_xz":
        def result(x, y, z):
            y = f(x, z)
            return x, y, z

        return result

    if argspec == "z_xz":
        def result(x, y, z):
            z = f(x, z)
            return x, y, z

        return result

    if argspec == "xy_xz":
        def result(x, y, z):
            x, y = f(x, z)
            return x, y, z

        return result

    if argspec == "xz_xz":
        def result(x, y, z):
            x, z = f(x, z)
            return x, y, z

        return result

    if argspec == "yx_xz":
        def result(x, y, z):
            y, x = f(x, z)
            return x, y, z

        return result

    if argspec == "yz_xz":
        def result(x, y, z):
            y, z = f(x, z)
            return x, y, z

        return result

    if argspec == "zx_xz":
        def result(x, y, z):
            z, x = f(x, z)
            return x, y, z

        return result

    if argspec == "zy_xz":
        def result(x, y, z):
            z, y = f(x, z)
            return x, y, z

        return result

    if argspec == "xyz_xz":
        def result(x, y, z):
            x, y, z = f(x, z)
            return x, y, z

        return result

    if argspec == "xzy_xz":
        def result(x, y, z):
            x, z, y = f(x, z)
            return x, y, z

        return result

    if argspec == "yxz_xz":
        def result(x, y, z):
            y, x, z = f(x, z)
            return x, y, z

        return result

    if argspec == "yzx_xz":
        def result(x, y, z):
            y, z, x = f(x, z)
            return x, y, z

        return result

    if argspec == "zxy_xz":
        def result(x, y, z):
            z, x, y = f(x, z)
            return x, y, z

        return result

    if argspec == "zyx_xz":
        def result(x, y, z):
            z, y, x = f(x, z)
            return x, y, z

        return result

    if argspec == "x_yx":
        def result(x, y, z):
            x = f(y, x)
            return x, y, z

        return result

    if argspec == "y_yx":
        def result(x, y, z):
            y = f(y, x)
            return x, y, z

        return result

    if argspec == "z_yx":
        def result(x, y, z):
            z = f(y, x)
            return x, y, z

        return result

    if argspec == "xy_yx":
        def result(x, y, z):
            x, y = f(y, x)
            return x, y, z

        return result

    if argspec == "xz_yx":
        def result(x, y, z):
            x, z = f(y, x)
            return x, y, z

        return result

    if argspec == "yx_yx":
        def result(x, y, z):
            y, x = f(y, x)
            return x, y, z

        return result

    if argspec == "yz_yx":
        def result(x, y, z):
            y, z = f(y, x)
            return x, y, z

        return result

    if argspec == "zx_yx":
        def result(x, y, z):
            z, x = f(y, x)
            return x, y, z

        return result

    if argspec == "zy_yx":
        def result(x, y, z):
            z, y = f(y, x)
            return x, y, z

        return result

    if argspec == "xyz_yx":
        def result(x, y, z):
            x, y, z = f(y, x)
            return x, y, z

        return result

    if argspec == "xzy_yx":
        def result(x, y, z):
            x, z, y = f(y, x)
            return x, y, z

        return result

    if argspec == "yxz_yx":
        def result(x, y, z):
            y, x, z = f(y, x)
            return x, y, z

        return result

    if argspec == "yzx_yx":
        def result(x, y, z):
            y, z, x = f(y, x)
            return x, y, z

        return result

    if argspec == "zxy_yx":
        def result(x, y, z):
            z, x, y = f(y, x)
            return x, y, z

        return result

    if argspec == "zyx_yx":
        def result(x, y, z):
            z, y, x = f(y, x)
            return x, y, z

        return result

    if argspec == "x_yz":
        def result(x, y, z):
            x = f(y, z)
            return x, y, z

        return result

    if argspec == "y_yz":
        def result(x, y, z):
            y = f(y, z)
            return x, y, z

        return result

    if argspec == "z_yz":
        def result(x, y, z):
            z = f(y, z)
            return x, y, z

        return result

    if argspec == "xy_yz":
        def result(x, y, z):
            x, y = f(y, z)
            return x, y, z

        return result

    if argspec == "xz_yz":
        def result(x, y, z):
            x, z = f(y, z)
            return x, y, z

        return result

    if argspec == "yx_yz":
        def result(x, y, z):
            y, x = f(y, z)
            return x, y, z

        return result

    if argspec == "yz_yz":
        def result(x, y, z):
            y, z = f(y, z)
            return x, y, z

        return result

    if argspec == "zx_yz":
        def result(x, y, z):
            z, x = f(y, z)
            return x, y, z

        return result

    if argspec == "zy_yz":
        def result(x, y, z):
            z, y = f(y, z)
            return x, y, z

        return result

    if argspec == "xyz_yz":
        def result(x, y, z):
            x, y, z = f(y, z)
            return x, y, z

        return result

    if argspec == "xzy_yz":
        def result(x, y, z):
            x, z, y = f(y, z)
            return x, y, z

        return result

    if argspec == "yxz_yz":
        def result(x, y, z):
            y, x, z = f(y, z)
            return x, y, z

        return result

    if argspec == "yzx_yz":
        def result(x, y, z):
            y, z, x = f(y, z)
            return x, y, z

        return result

    if argspec == "zxy_yz":
        def result(x, y, z):
            z, x, y = f(y, z)
            return x, y, z

        return result

    if argspec == "zyx_yz":
        def result(x, y, z):
            z, y, x = f(y, z)
            return x, y, z

        return result

    if argspec == "x_zx":
        def result(x, y, z):
            x = f(z, x)
            return x, y, z

        return result

    if argspec == "y_zx":
        def result(x, y, z):
            y = f(z, x)
            return x, y, z

        return result

    if argspec == "z_zx":
        def result(x, y, z):
            z = f(z, x)
            return x, y, z

        return result

    if argspec == "xy_zx":
        def result(x, y, z):
            x, y = f(z, x)
            return x, y, z

        return result

    if argspec == "xz_zx":
        def result(x, y, z):
            x, z = f(z, x)
            return x, y, z

        return result

    if argspec == "yx_zx":
        def result(x, y, z):
            y, x = f(z, x)
            return x, y, z

        return result

    if argspec == "yz_zx":
        def result(x, y, z):
            y, z = f(z, x)
            return x, y, z

        return result

    if argspec == "zx_zx":
        def result(x, y, z):
            z, x = f(z, x)
            return x, y, z

        return result

    if argspec == "zy_zx":
        def result(x, y, z):
            z, y = f(z, x)
            return x, y, z

        return result

    if argspec == "xyz_zx":
        def result(x, y, z):
            x, y, z = f(z, x)
            return x, y, z

        return result

    if argspec == "xzy_zx":
        def result(x, y, z):
            x, z, y = f(z, x)
            return x, y, z

        return result

    if argspec == "yxz_zx":
        def result(x, y, z):
            y, x, z = f(z, x)
            return x, y, z

        return result

    if argspec == "yzx_zx":
        def result(x, y, z):
            y, z, x = f(z, x)
            return x, y, z

        return result

    if argspec == "zxy_zx":
        def result(x, y, z):
            z, x, y = f(z, x)
            return x, y, z

        return result

    if argspec == "zyx_zx":
        def result(x, y, z):
            z, y, x = f(z, x)
            return x, y, z

        return result

    if argspec == "x_zy":
        def result(x, y, z):
            x = f(z, y)
            return x, y, z

        return result

    if argspec == "y_zy":
        def result(x, y, z):
            y = f(z, y)
            return x, y, z

        return result

    if argspec == "z_zy":
        def result(x, y, z):
            z = f(z, y)
            return x, y, z

        return result

    if argspec == "xy_zy":
        def result(x, y, z):
            x, y = f(z, y)
            return x, y, z

        return result

    if argspec == "xz_zy":
        def result(x, y, z):
            x, z = f(z, y)
            return x, y, z

        return result

    if argspec == "yx_zy":
        def result(x, y, z):
            y, x = f(z, y)
            return x, y, z

        return result

    if argspec == "yz_zy":
        def result(x, y, z):
            y, z = f(z, y)
            return x, y, z

        return result

    if argspec == "zx_zy":
        def result(x, y, z):
            z, x = f(z, y)
            return x, y, z

        return result

    if argspec == "zy_zy":
        def result(x, y, z):
            z, y = f(z, y)
            return x, y, z

        return result

    if argspec == "xyz_zy":
        def result(x, y, z):
            x, y, z = f(z, y)
            return x, y, z

        return result

    if argspec == "xzy_zy":
        def result(x, y, z):
            x, z, y = f(z, y)
            return x, y, z

        return result

    if argspec == "yxz_zy":
        def result(x, y, z):
            y, x, z = f(z, y)
            return x, y, z

        return result

    if argspec == "yzx_zy":
        def result(x, y, z):
            y, z, x = f(z, y)
            return x, y, z

        return result

    if argspec == "zxy_zy":
        def result(x, y, z):
            z, x, y = f(z, y)
            return x, y, z

        return result

    if argspec == "zyx_zy":
        def result(x, y, z):
            z, y, x = f(z, y)
            return x, y, z

        return result

    if argspec == "x_xyz":
        def result(x, y, z):
            x = f(x, y, z)
            return x, y, z

        return result

    if argspec == "y_xyz":
        def result(x, y, z):
            y = f(x, y, z)
            return x, y, z

        return result

    if argspec == "z_xyz":
        def result(x, y, z):
            z = f(x, y, z)
            return x, y, z

        return result

    if argspec == "xy_xyz":
        def result(x, y, z):
            x, y = f(x, y, z)
            return x, y, z

        return result

    if argspec == "xz_xyz":
        def result(x, y, z):
            x, z = f(x, y, z)
            return x, y, z

        return result

    if argspec == "yx_xyz":
        def result(x, y, z):
            y, x = f(x, y, z)
            return x, y, z

        return result

    if argspec == "yz_xyz":
        def result(x, y, z):
            y, z = f(x, y, z)
            return x, y, z

        return result

    if argspec == "zx_xyz":
        def result(x, y, z):
            z, x = f(x, y, z)
            return x, y, z

        return result

    if argspec == "zy_xyz":
        def result(x, y, z):
            z, y = f(x, y, z)
            return x, y, z

        return result

    if argspec == "xyz_xyz":
        def result(x, y, z):
            x, y, z = f(x, y, z)
            return x, y, z

        return result

    if argspec == "xzy_xyz":
        def result(x, y, z):
            x, z, y = f(x, y, z)
            return x, y, z

        return result

    if argspec == "yxz_xyz":
        def result(x, y, z):
            y, x, z = f(x, y, z)
            return x, y, z

        return result

    if argspec == "yzx_xyz":
        def result(x, y, z):
            y, z, x = f(x, y, z)
            return x, y, z

        return result

    if argspec == "zxy_xyz":
        def result(x, y, z):
            z, x, y = f(x, y, z)
            return x, y, z

        return result

    if argspec == "zyx_xyz":
        def result(x, y, z):
            z, y, x = f(x, y, z)
            return x, y, z

        return result

    if argspec == "x_xzy":
        def result(x, y, z):
            x = f(x, z, y)
            return x, y, z

        return result

    if argspec == "y_xzy":
        def result(x, y, z):
            y = f(x, z, y)
            return x, y, z

        return result

    if argspec == "z_xzy":
        def result(x, y, z):
            z = f(x, z, y)
            return x, y, z

        return result

    if argspec == "xy_xzy":
        def result(x, y, z):
            x, y = f(x, z, y)
            return x, y, z

        return result

    if argspec == "xz_xzy":
        def result(x, y, z):
            x, z = f(x, z, y)
            return x, y, z

        return result

    if argspec == "yx_xzy":
        def result(x, y, z):
            y, x = f(x, z, y)
            return x, y, z

        return result

    if argspec == "yz_xzy":
        def result(x, y, z):
            y, z = f(x, z, y)
            return x, y, z

        return result

    if argspec == "zx_xzy":
        def result(x, y, z):
            z, x = f(x, z, y)
            return x, y, z

        return result

    if argspec == "zy_xzy":
        def result(x, y, z):
            z, y = f(x, z, y)
            return x, y, z

        return result

    if argspec == "xyz_xzy":
        def result(x, y, z):
            x, y, z = f(x, z, y)
            return x, y, z

        return result

    if argspec == "xzy_xzy":
        def result(x, y, z):
            x, z, y = f(x, z, y)
            return x, y, z

        return result

    if argspec == "yxz_xzy":
        def result(x, y, z):
            y, x, z = f(x, z, y)
            return x, y, z

        return result

    if argspec == "yzx_xzy":
        def result(x, y, z):
            y, z, x = f(x, z, y)
            return x, y, z

        return result

    if argspec == "zxy_xzy":
        def result(x, y, z):
            z, x, y = f(x, z, y)
            return x, y, z

        return result

    if argspec == "zyx_xzy":
        def result(x, y, z):
            z, y, x = f(x, z, y)
            return x, y, z

        return result

    if argspec == "x_yxz":
        def result(x, y, z):
            x = f(y, x, z)
            return x, y, z

        return result

    if argspec == "y_yxz":
        def result(x, y, z):
            y = f(y, x, z)
            return x, y, z

        return result

    if argspec == "z_yxz":
        def result(x, y, z):
            z = f(y, x, z)
            return x, y, z

        return result

    if argspec == "xy_yxz":
        def result(x, y, z):
            x, y = f(y, x, z)
            return x, y, z

        return result

    if argspec == "xz_yxz":
        def result(x, y, z):
            x, z = f(y, x, z)
            return x, y, z

        return result

    if argspec == "yx_yxz":
        def result(x, y, z):
            y, x = f(y, x, z)
            return x, y, z

        return result

    if argspec == "yz_yxz":
        def result(x, y, z):
            y, z = f(y, x, z)
            return x, y, z

        return result

    if argspec == "zx_yxz":
        def result(x, y, z):
            z, x = f(y, x, z)
            return x, y, z

        return result

    if argspec == "zy_yxz":
        def result(x, y, z):
            z, y = f(y, x, z)
            return x, y, z

        return result

    if argspec == "xyz_yxz":
        def result(x, y, z):
            x, y, z = f(y, x, z)
            return x, y, z

        return result

    if argspec == "xzy_yxz":
        def result(x, y, z):
            x, z, y = f(y, x, z)
            return x, y, z

        return result

    if argspec == "yxz_yxz":
        def result(x, y, z):
            y, x, z = f(y, x, z)
            return x, y, z

        return result

    if argspec == "yzx_yxz":
        def result(x, y, z):
            y, z, x = f(y, x, z)
            return x, y, z

        return result

    if argspec == "zxy_yxz":
        def result(x, y, z):
            z, x, y = f(y, x, z)
            return x, y, z

        return result

    if argspec == "zyx_yxz":
        def result(x, y, z):
            z, y, x = f(y, x, z)
            return x, y, z

        return result

    if argspec == "x_yzx":
        def result(x, y, z):
            x = f(y, z, x)
            return x, y, z

        return result

    if argspec == "y_yzx":
        def result(x, y, z):
            y = f(y, z, x)
            return x, y, z

        return result

    if argspec == "z_yzx":
        def result(x, y, z):
            z = f(y, z, x)
            return x, y, z

        return result

    if argspec == "xy_yzx":
        def result(x, y, z):
            x, y = f(y, z, x)
            return x, y, z

        return result

    if argspec == "xz_yzx":
        def result(x, y, z):
            x, z = f(y, z, x)
            return x, y, z

        return result

    if argspec == "yx_yzx":
        def result(x, y, z):
            y, x = f(y, z, x)
            return x, y, z

        return result

    if argspec == "yz_yzx":
        def result(x, y, z):
            y, z = f(y, z, x)
            return x, y, z

        return result

    if argspec == "zx_yzx":
        def result(x, y, z):
            z, x = f(y, z, x)
            return x, y, z

        return result

    if argspec == "zy_yzx":
        def result(x, y, z):
            z, y = f(y, z, x)
            return x, y, z

        return result

    if argspec == "xyz_yzx":
        def result(x, y, z):
            x, y, z = f(y, z, x)
            return x, y, z

        return result

    if argspec == "xzy_yzx":
        def result(x, y, z):
            x, z, y = f(y, z, x)
            return x, y, z

        return result

    if argspec == "yxz_yzx":
        def result(x, y, z):
            y, x, z = f(y, z, x)
            return x, y, z

        return result

    if argspec == "yzx_yzx":
        def result(x, y, z):
            y, z, x = f(y, z, x)
            return x, y, z

        return result

    if argspec == "zxy_yzx":
        def result(x, y, z):
            z, x, y = f(y, z, x)
            return x, y, z

        return result

    if argspec == "zyx_yzx":
        def result(x, y, z):
            z, y, x = f(y, z, x)
            return x, y, z

        return result

    if argspec == "x_zxy":
        def result(x, y, z):
            x = f(z, x, y)
            return x, y, z

        return result

    if argspec == "y_zxy":
        def result(x, y, z):
            y = f(z, x, y)
            return x, y, z

        return result

    if argspec == "z_zxy":
        def result(x, y, z):
            z = f(z, x, y)
            return x, y, z

        return result

    if argspec == "xy_zxy":
        def result(x, y, z):
            x, y = f(z, x, y)
            return x, y, z

        return result

    if argspec == "xz_zxy":
        def result(x, y, z):
            x, z = f(z, x, y)
            return x, y, z

        return result

    if argspec == "yx_zxy":
        def result(x, y, z):
            y, x = f(z, x, y)
            return x, y, z

        return result

    if argspec == "yz_zxy":
        def result(x, y, z):
            y, z = f(z, x, y)
            return x, y, z

        return result

    if argspec == "zx_zxy":
        def result(x, y, z):
            z, x = f(z, x, y)
            return x, y, z

        return result

    if argspec == "zy_zxy":
        def result(x, y, z):
            z, y = f(z, x, y)
            return x, y, z

        return result

    if argspec == "xyz_zxy":
        def result(x, y, z):
            x, y, z = f(z, x, y)
            return x, y, z

        return result

    if argspec == "xzy_zxy":
        def result(x, y, z):
            x, z, y = f(z, x, y)
            return x, y, z

        return result

    if argspec == "yxz_zxy":
        def result(x, y, z):
            y, x, z = f(z, x, y)
            return x, y, z

        return result

    if argspec == "yzx_zxy":
        def result(x, y, z):
            y, z, x = f(z, x, y)
            return x, y, z

        return result

    if argspec == "zxy_zxy":
        def result(x, y, z):
            z, x, y = f(z, x, y)
            return x, y, z

        return result

    if argspec == "zyx_zxy":
        def result(x, y, z):
            z, y, x = f(z, x, y)
            return x, y, z

        return result

    if argspec == "x_zyx":
        def result(x, y, z):
            x = f(z, y, x)
            return x, y, z

        return result

    if argspec == "y_zyx":
        def result(x, y, z):
            y = f(z, y, x)
            return x, y, z

        return result

    if argspec == "z_zyx":
        def result(x, y, z):
            z = f(z, y, x)
            return x, y, z

        return result

    if argspec == "xy_zyx":
        def result(x, y, z):
            x, y = f(z, y, x)
            return x, y, z

        return result

    if argspec == "xz_zyx":
        def result(x, y, z):
            x, z = f(z, y, x)
            return x, y, z

        return result

    if argspec == "yx_zyx":
        def result(x, y, z):
            y, x = f(z, y, x)
            return x, y, z

        return result

    if argspec == "yz_zyx":
        def result(x, y, z):
            y, z = f(z, y, x)
            return x, y, z

        return result

    if argspec == "zx_zyx":
        def result(x, y, z):
            z, x = f(z, y, x)
            return x, y, z

        return result

    if argspec == "zy_zyx":
        def result(x, y, z):
            z, y = f(z, y, x)
            return x, y, z

        return result

    if argspec == "xyz_zyx":
        def result(x, y, z):
            x, y, z = f(z, y, x)
            return x, y, z

        return result

    if argspec == "xzy_zyx":
        def result(x, y, z):
            x, z, y = f(z, y, x)
            return x, y, z

        return result

    if argspec == "yxz_zyx":
        def result(x, y, z):
            y, x, z = f(z, y, x)
            return x, y, z

        return result

    if argspec == "yzx_zyx":
        def result(x, y, z):
            y, z, x = f(z, y, x)
            return x, y, z

        return result

    if argspec == "zxy_zyx":
        def result(x, y, z):
            z, x, y = f(z, y, x)
            return x, y, z

        return result

    if argspec == "zyx_zyx":
        def result(x, y, z):
            z, y, x = f(z, y, x)
            return x, y, z

        return result


    raise Error()
